version: "3.8"

services:
  # mysql:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: suman
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - .dbdata:/var/lib/mysql/eventsDB

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: suman
      POSTGRES_PASSWORD: suman
      POSTGRES_DB: nest-events
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgres/eventsDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
